apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-deployment
  labels:
    name: guusto-balance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance
  template:
    metadata:
      labels:
        app: balance
    spec:
      containers:
        - name:  guusto-balance
          image: guusto/guusto-balance:latest
          ports:
            - containerPort: 8082
              name: "http"
